[package]
name = "aistore"
version = "0.1.0"
edition = "2024"

[dependencies]
jemallocator = "0.5.4"
jemalloc-sys = "0.5.4"
rand = "0.8.5"
xxhash-rust = { version = "0.8.12", features = ["xxh64"] }
simplehash = "0.1.3"
crc32fast = "1.5.0"


